### ISSUE TITLE
Images are not showing up

### ISSUE THREAD

**Issue by pham0188** [pham0188/Picture-This#1]
@wendywarren

Dear professor, my name is Thi Ngan Giang Pham from Web Dev II mtm6201-040. 
I have done with my code for the "Picture This!" assignment. However, when I "go live", it just didn't show my images. I checked spelling, naming conventions, and even the folders, but I think they are all fine. Do I miss anything? the "images" folder (which contains 7 images in total) is in the same place with index.html and style.css. 

`<picture>
      <source srcset="images/museum-320.jpg,
                      images/museum-640.jpg 2x,
                      images/museum-960.jpg 3x"
              media="(max-width: 320px)">

      <source srcset="images/museum2-480.jpg,
                      images/museum2-960.jpg 2x,
                      images/museum2-1440.jpg 3x"
              media="(max-width: 480px)">

      <source srcset="images/museum-720.jpg,
                      images/museum-1440.jpg 2x,
                      images/museum-2160.jpg 3x"
              media="(max-width: 720px)">

      <source srcset="images/museum-960.jpg,
                      images/museum-1920.jpg 2x,
                      images/museum-2880.jpg 3x"
               media="(max-width: 959px)">

        <source srcset="images/museum-800.jpg,
                        images/museum-1600.jpg 2x,
                        images/museum-2400.jpg 3x"
                media="(min-width: 1600px)">

        <source srcset="images/museum-640.jpg,
                        images/museum-1280.jpg 2x,
                        images/museum-1920.jpg 3x"
                media="(min-width: 1280px)">

        <source srcset="images/museum-480.jpg,
                        images/museum-960.jpg 2x,
                        images/museum-1440.jpg 3x"
                media="(min-width: 960px)">

        <img src="images/museum.jpg" alt="A picture of a museum">
</picture>`

Please help me :( Thank you so much.

**Comment by pham0188** [comment]
Or do i have to resize all the sizes in the table :(?

**Comment by wendywarren** [comment]
Hi @pham0188,

Yes, you would need to resize the image for every value under each heading of 1x, 2x and 3x.

This amounts to I believe 9 landscape and 9 square.

Wendy

**Comment by pham0188** [comment]
> Hi @pham0188,
> 
> Yes, you would need to resize the image for every value under each heading of 1x, 2x and 3x.
> 
> This amounts to I believe 9 landscape and 9 square.
> 
> Wendy

Thank you so much! I solved it
